remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: "air"   # "default", "dark", "neon", "contrast" vb. deneyebilirsin
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
url: "https://agkirici.github.io"
baseurl: ""
title: "AGK"
description: "Molecular Biologist → Bioinformatics / Software"
