remote_theme: mmistakes/minimal-mistakes
title: Arzu Kirici
description: Biologist/Bioinformatics/Software Developer


nav:
  - name: "About"
    link: /
  - name: "Projects"
    link: /projects
  - name: "Blog"
    link: /blog
