# main text of home
title: Arzu Kirici, MSc
bio: Scientist passionate about spatial biology, data analysis, computational tools, and developing software.

external-image: false
picture: assets/images/profilee.png

dark-theme: auto

resume: true
resume-external: true
resume-url: https://agkirici.github.io/Arzu_Kirici_CV.pdf  # sondaki /'ı kaldır

url: https://agkirici.github.io
baseurl: ""   # user site için boş; project site ise "/<repo-adi>"

linkedin: arzu-kirici
github: agkirici
email: arzukirici@gmail.com

authors:
  arzu:
    name: Arzu Kirici
    bio: Traveling the world, doing science.
    external-image: false
    picture: assets/images/profile.jpg

width: large   # (normal/large)
