theme: jekyll-theme-minimal
title: Arzu Kirici
description: Molecular Biologist → Bioinformatician/Software Developer

nav:
  - name: "About"
    link: /
  - name: "Projects"
    link: /projects
  - name: "Blog"
    link: /blog
