remote_theme: mmistakes/minimal-mistakes
title: "Arzu Kirici"
description: "Bioinformatics • Spatial/Single-cell • Software"
plugins:
  - jekyll-include-cache
  - jekyll-remote-theme
markdown: kramdown
kramdown:
  input: GFM
